#!/bin/sh
# chkconfig: 345 22 10
# description: WINS Virtualbox Configuration
#
# Set ORA_OWNER to the user id of the owner of the
# Oracle software.

. /etc/rc.d/init.d/functions

export ORACLE_OWNER=oracle

service_name="WInS Virtualbox Configuration"
logger="/usr/bin/logger -t rc.local "


start_service()
{
	echo -n "Starting ${service_name}: "

  #cp /u01/content/weblogic-innovation-seminars/WInS_Demos/control/network/ifcfg-eth4 /etc/sysconfig/network-scripts
  success
  echo
}

stop_service()
{
	echo -n "Stopping ${service_name} is not supported: "
  success
  echo ""
}

case "$1" in
    'start')
				start_service
        ;;
    'stop')
    		stop_service
        ;;
    'restart')
				stop_service
				start_service
        ;;
esac
